# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Kristopher Bredemeier'
tagline:          'Web Developer from Bonn, Germany'
description:      'A blog about the daily struggles of beeing a software developer.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Kristopher Bredemeier'
  url:            https://twitter.com/piratenpete

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
